name: chess_game
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked: ^3.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/board.png
    - lib/assets/black_king.png
    - lib/assets/black_queen.png
    - lib/assets/black_bishop.png
    - lib/assets/black_knight.png
    - lib/assets/black_rook.png
    - lib/assets/black_pawn.png
    - lib/assets/white_king.png
    - lib/assets/white_queen.png
    - lib/assets/white_bishop.png
    - lib/assets/white_knight.png
    - lib/assets/white_rook.png
    - lib/assets/white_pawn.png
    - lib/assets/select_dot_small.png
    - lib/assets/select_dot_big.png
